baseURL: https://biophilross.github.io
languageCode: en-US
title: Philipp Ross
disqusShortname: ''
googleAnalytics: ''
theme: hugo-sustain
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
permalinks:
  post: /:year/:month/:day/:slug
params:
  author: Philipp Ross
  avatar: img/profile.jpg
  custom_css: []
  custom_js: []
  description: Personal website
  social:
    Email: philross@uchicago.edu
    Github: biophilross
    LinkedIn: philippross
    Scholar: cairIiQAAAAJ
    RSS: /posts/index.xml
    Twitter: biophilross
menu:
  main:
    - identifier: projects
      name: projects
      url: /projects/
      weight: 100
    - identifier: posts
      name: posts
      url: /posts/
      weight: 200
    - identifier: resources
      name: resources
      url: /resources/
      weight: 300
markup:
  goldmark:
    renderer:
      unsafe: true
publishDir: '../biophilross.github.io'
